plugins:
  postcss-import: {}
  postcss-cssnext: {}
  postcss-smart-import: {}
  precss: {}
  autoprefixer: {}
  # postcss-assets: {
  #   loadPaths: ['images', '../app/assets_src/images/'],
  #   basePath: 'public',
  #   cachebuster: true,
  # }
